image:
  file: .gitpod.Dockerfile
tasks:
  - name: setup
    before: |
      # REMOVE USER VALIDATION -Y ON JAVA 17 INSTALLATION
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config

      # JAVA 17 INSTALL
      sdk install java

      curl -Ls "https://dtsx.io/get-astra-cli" | bash

    command: |
      gp open README.md
      unset JAVA_TOOL_OPTIONS

      # prep files for workshop
      rm src/main/java/com/datastaxtutorials/livecodingdemo/HolidayController.java
      mv src/main/java/com/datastaxtutorials/livecodingdemo/HolidayController.java_empty src/main/java/com/datastaxtutorials/livecodingdemo/HolidayController.java

      source /home/gitpod/.astra/cli/astra-init.sh
      # astra setup
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
